# site settings
title: twentyseven.dev
subtitle:
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://twentyseven.dev" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/daniel-white
gitlab_url:
googleplus_url: 
instagram_url: https://instagram.com/danielallanwhite
linkedin_url: https://www.linkedin.com/in/danielawhite
pinterest_url:
slack_url:
stack_overflow_url: https://stackoverflow.com/users/23528/daniel-a-white
twitter_url: https://twitter.com/thetrueaplus

# build settings
markdown: kramdown

sass:
  style: compressed
